<?php
/**
 * The front page array
 *
 * @package genesis-design-pro
 */

return array(
	'after-content-featured-widget-setup'                 => array(
		'title' => __( 'Area Setup', 'gppro' ),
		'data'  => array(
			'after-content-featured-back' => array(
				'label'    => __( 'Background Color', 'gppro' ),
				'input'    => 'color',
				'target'   => '.after-content-featured',
				'builder'  => 'GP_Pro_Builder::hexcolor_css',
				'selector' => 'background-color',
			),
		),
	),
	'after-content-featured-setup'                        => array(
		'title' => __( 'Padding', 'gppro' ),
		'data'  => array(
			'after-content-featured-padding-top'    => array(
				'label'    => __( 'Top', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.after-content-featured',
				'builder'  => 'GP_Pro_Builder::pct_css',
				'selector' => 'padding-top',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'after-content-featured-padding-bottom' => array(
				'label'    => __( 'Bottom', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.after-content-featured',
				'builder'  => 'GP_Pro_Builder::pct_css',
				'selector' => 'padding-bottom',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'after-content-featured-padding-left'   => array(
				'label'    => __( 'Left', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.after-content-featured',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-left',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'after-content-featured-padding-right'  => array(
				'label'    => __( 'Right', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.after-content-featured',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-right',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
		),
	),

	'section-break-after-content-featured-single-widget'  => array(
		'break' => array(
			'type'  => 'full',
			'title' => __( 'Single Widgets', 'gppro' ),
		),
	),

	'after-content-featured-widget-padding-setup'         => array(
		'title' => __( 'Widget Padding', 'gppro' ),
		'data'  => array(
			'after-content-featured-widget-padding-top'    => array(
				'label'    => __( 'Top', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.after-content-featured .entry',
				'builder'  => 'GP_Pro_Builder::pct_css',
				'selector' => 'padding-top',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'after-content-featured-widget-padding-bottom' => array(
				'label'    => __( 'Bottom', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.after-content-featured .entry',
				'builder'  => 'GP_Pro_Builder::pct_css',
				'selector' => 'padding-bottom',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'after-content-featured-widget-padding-left'   => array(
				'label'    => __( 'Left', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.after-content-featured .entry',
				'builder'  => 'GP_Pro_Builder::pct_css',
				'selector' => 'padding-left',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'after-content-featured-widget-padding-right'  => array(
				'label'    => __( 'Right', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.after-content-featured .entry',
				'builder'  => 'GP_Pro_Builder::pct_css',
				'selector' => 'padding-right',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
		),
	),

	'section-break-after-content-featured-entry-title'    => array(
		'break' => array(
			'type'  => 'thin',
			'title' => __( 'Featured Title', 'gppro' ),
		),
	),
	'after-content-featured-post-entry-title-color'       => array(
		'title' => 'Colors',
		'data'  => array(
			'after-content-featured-entry-title-link'     => array(
				'label'    => __( 'Link', 'gppro' ),
				'sub'      => __( 'Base', 'gppro' ),
				'input'    => 'color',
				'target'   => '.after-content-featured .featuredpage .entry .entry-header a',
				'builder'  => 'GP_Pro_Builder::hexcolor_css',
				'selector' => 'color',
			),
			'after-content-featured-entry-title-link-hov' => array(
				'label'        => __( 'Link', 'gppro' ),
				'sub'          => __( 'Hover', 'gppro' ),
				'input'        => 'color',
				'target'       => array( '.after-content-featured .featuredpage .entry .entry-header a:hover', '.after-content-featured .featuredpage .entry .entry-header a:focus' ),
				'builder'      => 'GP_Pro_Builder::hexcolor_css',
				'selector'     => 'color',
				'always_write' => true,
			),
		),
	),
	'after-content-featured-post-entry-title'             => array(
		'title' => 'Typography',
		'data'  => array(
			'after-content-featured-entry-title-stack'     => array(
				'label'    => __( 'Font Stack', 'gppro' ),
				'input'    => 'font-stack',
				'target'   => '.after-content-featured .entry .entry-title',
				'builder'  => 'GP_Pro_Builder::stack_css',
				'selector' => 'font-family',
			),
			'after-content-featured-entry-title-size'      => array(
				'label'    => __( 'Font Size', 'gppro' ),
				'input'    => 'font-size',
				'scale'    => 'text',
				'target'   => '.after-content-featured .entry .entry-title',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'font-size',
			),
			'after-content-featured-entry-title-weight'    => array(
				'label'    => __( 'Font Weight', 'gppro' ),
				'input'    => 'font-weight',
				'target'   => '.after-content-featured .entry .entry-title',
				'builder'  => 'GP_Pro_Builder::number_css',
				'selector' => 'font-weight',
				'tip'      => __( 'Certain fonts will not display every weight.', 'gppro' ),
			),
			'after-content-featured-entry-title-transform' => array(
				'label'    => __( 'Text Appearance', 'gppro' ),
				'input'    => 'text-transform',
				'target'   => '.after-content-featured .entry .entry-title',
				'builder'  => 'GP_Pro_Builder::text_css',
				'selector' => 'text-transform',
			),
			'after-content-featured-entry-title-style'     => array(
				'label'    => __( 'Font Style', 'gppro' ),
				'input'    => 'radio',
				'options'  => array(
					array(
						'label' => __( 'Normal', 'gppro' ),
						'value' => 'normal',
					),
					array(
						'label' => __( 'Italic', 'gppro' ),
						'value' => 'italic',
					),
				),
				'target'   => '.after-content-featured .entry .entry-title',
				'builder'  => 'GP_Pro_Builder::text_css',
				'selector' => 'font-style',
			),
		),
	),

	'after-content-featured-entry-title-padding-setup'    => array(
		'title' => 'Featured Title Padding',
		'data'  => array(
			'after-content-featured-entry-title-padding-top'  => array(
				'label'    => __( 'Top', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.after-content-featured .entry-header',
				'builder'  => 'GP_Pro_Builder::pct_css',
				'selector' => 'padding-top',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'after-content-featured-entry-title-padding-bottom' => array(
				'label'    => __( 'Bottom', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.after-content-featured .entry-header',
				'builder'  => 'GP_Pro_Builder::pct_css',
				'selector' => 'padding-bottom',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'after-content-featured-entry-title-padding-left' => array(
				'label'    => __( 'Left', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.after-content-featured .entry-header',
				'builder'  => 'GP_Pro_Builder::pct_css',
				'selector' => 'padding-left',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'after-content-featured-entry-title-padding-right' => array(
				'label'    => __( 'Right', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.after-content-featured .entry-header',
				'builder'  => 'GP_Pro_Builder::pct_css',
				'selector' => 'padding-right',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'after-content-featured-entry-title-margin-setup' => array(
				'title' => __( 'Featured Title Margin', 'gppro' ),
				'input' => 'divider',
				'style' => 'lines',
			),
			'after-content-featured-entry-title-margin-top'   => array(
				'label'    => __( 'Top Margin', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.after-content-featured .entry-header',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'margin-top',
				'min'      => '0',
				'max'      => '36',
				'step'     => '2',
			),
			'after-content-featured-entry-title-margin-bottom' => array(
				'label'    => __( 'Bottom Margin', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.after-content-featured .entry-header',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'margin-bottom',
				'min'      => '0',
				'max'      => '36',
				'step'     => '2',
			),
			'after-content-featured-entry-title-margin-left'  => array(
				'label'    => __( 'Left Margin', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.after-content-featured .entry-header',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'margin-left',
				'min'      => '-60',
				'max'      => '36',
				'step'     => '2',
			),
			'after-content-featured-entry-title-margin-right' => array(
				'label'    => __( 'Right Margin', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.after-content-featured .entry-header',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'margin-right',
				'min'      => '-60',
				'max'      => '36',
				'step'     => '2',
			),
			'after-content-featured-widget-message-divider'   => array(
				'text'  => __( 'Featured Title Margin can be adjusted to re-align title and bottom border if Single Widget padding is adjusted.', 'gppro' ),
				'input' => 'divider',
				'style' => 'block-thin',
			),
		),
	),

	'section-break-after-content-featured-widget-content' => array(
		'break' => array(
			'type'  => 'thin',
			'title' => __( 'Widget Content', 'gppro' ),
		),
	),

	'after-content-featured-widget-content-setup'         => array(
		'title' => '',
		'data'  => array(
			'after-content-featured-widget-content-back'   => array(
				'label'    => __( 'Background Color', 'gppro' ),
				'input'    => 'color',
				'target'   => '.after-content-featured .widget .entry .entry-content',
				'builder'  => 'GP_Pro_Builder::hexcolor_css',
				'selector' => 'background-color',
			),
			'after-content-featured-widget-content-text'   => array(
				'label'    => __( 'Text', 'gppro' ),
				'input'    => 'color',
				'target'   => '.after-content-featured .entry .entry-content',
				'builder'  => 'GP_Pro_Builder::hexcolor_css',
				'selector' => 'color',
			),
			'after-content-featured-widget-content-stack'  => array(
				'label'    => __( 'Font Stack', 'gppro' ),
				'input'    => 'font-stack',
				'target'   => '.after-content-featured .entry .entry-content',
				'builder'  => 'GP_Pro_Builder::stack_css',
				'selector' => 'font-family',
			),
			'after-content-featured-widget-content-size'   => array(
				'label'    => __( 'Font Size', 'gppro' ),
				'input'    => 'font-size',
				'scale'    => 'text',
				'target'   => '.after-content-featured .entry .entry-content',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'font-size',
			),
			'after-content-featured-widget-content-weight' => array(
				'label'    => __( 'Font Weight', 'gppro' ),
				'input'    => 'font-weight',
				'target'   => '.after-content-featured .entry .entry-content',
				'builder'  => 'GP_Pro_Builder::number_css',
				'selector' => 'font-weight',
				'tip'      => __( 'Certain fonts will not display every weight.', 'gppro' ),
			),
			'after-content-featured-widget-content-transform' => array(
				'label'    => __( 'Text Appearance', 'gppro' ),
				'input'    => 'text-transform',
				'target'   => '.after-content-featured .entry .entry-content',
				'builder'  => 'GP_Pro_Builder::text_css',
				'selector' => 'text-transform',
			),
			'after-content-featured-widget-content-align'  => array(
				'label'        => __( 'Text Alignment', 'gppro' ),
				'input'        => 'text-align',
				'target'       => '.after-content-featured .entry .entry-content',
				'builder'      => 'GP_Pro_Builder::text_css',
				'selector'     => 'text-align',
				'always_write' => true,
			),
			'after-content-featured-widget-content-style'  => array(
				'label'    => __( 'Font Style', 'gppro' ),
				'input'    => 'radio',
				'options'  => array(
					array(
						'label' => __( 'Normal', 'gppro' ),
						'value' => 'normal',
					),
					array(
						'label' => __( 'Italic', 'gppro' ),
						'value' => 'italic',
					),
				),
				'target'   => '.after-content-featured .entry .entry-content',
				'builder'  => 'GP_Pro_Builder::text_css',
				'selector' => 'font-style',
			),
		),
	),

	'section-break-after-content-featured-widget-read-more' => array(
		'break' => array(
			'type'  => 'thin',
			'title' => __( 'Read More Link', 'gppro' ),
		),
	),
	'after-content-featured-read-more-color-setup'        => array(
		'title' => 'Colors',
		'data'  => array(
			'after-content-featured-read-more-link'     => array(
				'label'        => __( 'Link', 'gppro' ),
				'sub'          => __( 'base', 'gppro' ),
				'input'        => 'color',
				'target'       => '.after-content-featured a.more-link',
				'builder'      => 'GP_Pro_Builder::hexcolor_css',
				'selector'     => 'color',
				'always_write' => true,
			),
			'after-content-featured-read-more-link-hov' => array(
				'label'        => __( 'Link', 'gppro' ),
				'sub'          => __( 'Hover', 'gppro' ),
				'input'        => 'color',
				'target'       => array( '.after-content-featured a.more-link:hover, .after-content-featured a.more-link:focus' ),
				'builder'      => 'GP_Pro_Builder::hexcolor_css',
				'selector'     => 'color',
				'always_write' => true,
			),
			'after-content-featured-read-more-underline-color' => array(
				'label'        => __( 'Bottom Border Color', 'gppro' ),
				'input'        => 'color',
				'target'       => '.after-content-featured a.more-link',
				'builder'      => 'GP_Pro_Builder::hexcolor_css',
				'selector'     => 'border-bottom-color',
				'always_write' => true,
			),
			'after-content-featured-read-more-underline-hov' => array(
				'label'        => __( 'Bottom Border Color', 'gppro' ),
				'sub'          => __( 'Hover', 'gppro' ),
				'input'        => 'color',
				'target'       => array( '.after-content-featured a.more-link:hover, .after-content-featured a.more-link:focus' ),
				'builder'      => 'GP_Pro_Builder::hexcolor_css',
				'selector'     => 'border-bottom-color',
				'always_write' => true,
			),
			'after-content-featured-read-more-underline-style' => array(
				'label'    => __( 'Bottom Border Style', 'gppro' ),
				'input'    => 'borders',
				'target'   => '.after-content-featured a.more-link',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'border-bottom-style',
			),
			'after-content-featured-read-more-underline-width' => array(
				'label'    => __( 'Bottom Border Width', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.after-content-featured a.more-link',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'border-bottom-width',
				'min'      => '0',
				'max'      => '10',
				'step'     => '1',
			),
		),
	),
	'after-content-featured-read-more-setup'              => array(
		'title' => 'Typography',
		'data'  => array(
			'after-content-featured-read-more-stack'     => array(
				'label'    => __( 'Font Stack', 'gppro' ),
				'input'    => 'font-stack',
				'target'   => '.after-content-featured .more-link',
				'builder'  => 'GP_Pro_Builder::stack_css',
				'selector' => 'font-family',
			),
			'after-content-featured-read-more-size'      => array(
				'label'    => __( 'Font Size', 'gppro' ),
				'input'    => 'font-size',
				'scale'    => 'text',
				'target'   => '.after-content-featured .more-link',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'font-size',
			),
			'after-content-featured-read-more-weight'    => array(
				'label'    => __( 'Font Weight', 'gppro' ),
				'input'    => 'font-weight',
				'target'   => '.after-content-featured .more-link',
				'builder'  => 'GP_Pro_Builder::number_css',
				'selector' => 'font-weight',
				'tip'      => __( 'Certain fonts will not display every weight.', 'gppro' ),
			),
			'after-content-featured-read-more-transform' => array(
				'label'    => __( 'Text Appearance', 'gppro' ),
				'input'    => 'text-transform',
				'target'   => '.after-content-featured .more-link',
				'builder'  => 'GP_Pro_Builder::text_css',
				'selector' => 'text-transform',
			),
			'after-content-featured-read-more-align'     => array(
				'label'        => __( 'Text Alignment', 'gppro' ),
				'input'        => 'text-align',
				'target'       => '.after-content-featured .more-link',
				'builder'      => 'GP_Pro_Builder::text_css',
				'selector'     => 'text-align',
				'always_write' => true,
			),
			'after-content-featured-read-more-style'     => array(
				'label'    => __( 'Font Style', 'gppro' ),
				'input'    => 'radio',
				'options'  => array(
					array(
						'label' => __( 'Normal', 'gppro' ),
						'value' => 'normal',
					),
					array(
						'label' => __( 'Italic', 'gppro' ),
						'value' => 'italic',
					),
				),
				'target'   => '.after-content-featured .entry .more-link',
				'builder'  => 'GP_Pro_Builder::text_css',
				'selector' => 'font-style',
			),
		),
	),
);
