<?php
/**
 * The front page array
 *
 * @package genesis-design-pro
 */

return array(
	'section-break-hero-section'                      => array(
		'break' => array(
			'type'  => 'full',
			'title' => __( 'Hero Section', 'gppro' ),
			'text'  => __( 'This area is designs to display a welcome message and uses a signup form via the Genesis eNews widget.', 'gppro' ),
		),
	),

	'hero-title'                                      => array(
		'title' => __( 'Hero Title', 'gppro' ),
		'data'  => array(
			'hero-section-title-stack'     => array(
				'label'    => __( 'Font Stack', 'gppro' ),
				'input'    => 'font-stack',
				'target'   => '.hero-title',
				'builder'  => 'GP_Pro_Builder::stack_css',
				'selector' => 'font-family',
			),
			'hero-section-title-size'      => array(
				'label'    => __( 'Font Size', 'gppro' ),
				'input'    => 'font-size',
				'scale'    => 'text',
				'target'   => '.hero-title',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'font-size',
			),
			'hero-section-title-weight'    => array(
				'label'    => __( 'Font Weight', 'gppro' ),
				'input'    => 'font-weight',
				'target'   => '.hero-title',
				'builder'  => 'GP_Pro_Builder::number_css',
				'selector' => 'font-weight',
				'tip'      => __( 'Certain fonts will not display every weight.', 'gppro' ),
			),
			'hero-section-title-transform' => array(
				'label'    => __( 'Text Appearance', 'gppro' ),
				'input'    => 'text-transform',
				'target'   => '.hero-title',
				'builder'  => 'GP_Pro_Builder::text_css',
				'selector' => 'text-transform',
			),
			'hero-section-title-align'     => array(
				'label'        => __( 'Text Alignment', 'gppro' ),
				'input'        => 'text-align',
				'target'       => '.hero-title',
				'builder'      => 'GP_Pro_Builder::text_css',
				'selector'     => 'text-align',
				'always_write' => true,
			),
			'hero-section-title-style'     => array(
				'label'    => __( 'Font Style', 'gppro' ),
				'input'    => 'radio',
				'options'  => array(
					array(
						'label' => __( 'Normal', 'gppro' ),
						'value' => 'normal',
					),
					array(
						'label' => __( 'Italic', 'gppro' ),
						'value' => 'italic',
					),
				),
				'target'   => '.hero-title',
				'builder'  => 'GP_Pro_Builder::text_css',
				'selector' => 'font-style',
			),
		),
	),

	'hero-description'                                => array(
		'title' => __( 'Hero Description', 'gppro' ),
		'data'  => array(
			'hero-section-description-stack'     => array(
				'label'    => __( 'Font Stack', 'gppro' ),
				'input'    => 'font-stack',
				'target'   => '.hero-description',
				'builder'  => 'GP_Pro_Builder::stack_css',
				'selector' => 'font-family',
			),
			'hero-section-description-size'      => array(
				'label'    => __( 'Font Size', 'gppro' ),
				'input'    => 'font-size',
				'scale'    => 'text',
				'target'   => '.hero-description',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'font-size',
			),
			'hero-section-description-weight'    => array(
				'label'    => __( 'Font Weight', 'gppro' ),
				'input'    => 'font-weight',
				'target'   => '.hero-description',
				'builder'  => 'GP_Pro_Builder::number_css',
				'selector' => 'font-weight',
				'tip'      => __( 'Certain fonts will not display every weight.', 'gppro' ),
			),
			'hero-section-description-transform' => array(
				'label'    => __( 'Text Appearance', 'gppro' ),
				'input'    => 'text-transform',
				'target'   => '.hero-description',
				'builder'  => 'GP_Pro_Builder::text_css',
				'selector' => 'text-transform',
			),
			'hero-section-description-align'     => array(
				'label'        => __( 'Text Alignment', 'gppro' ),
				'input'        => 'text-align',
				'target'       => '.hero-description',
				'builder'      => 'GP_Pro_Builder::text_css',
				'selector'     => 'text-align',
				'always_write' => true,
			),
			'hero-section-description-style'     => array(
				'label'    => __( 'Font Style', 'gppro' ),
				'input'    => 'radio',
				'options'  => array(
					array(
						'label' => __( 'Normal', 'gppro' ),
						'value' => 'normal',
					),
					array(
						'label' => __( 'Italic', 'gppro' ),
						'value' => 'italic',
					),
				),
				'target'   => '.hero-description',
				'builder'  => 'GP_Pro_Builder::text_css',
				'selector' => 'font-style',
			),
		),
	),

	'hero-section-setup'                              => array(
		'title' => __( 'Padding', 'gppro' ),
		'data'  => array(
			'hero-section-padding-top'    => array(
				'label'    => __( 'Top', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.hero-section',
				'builder'  => 'GP_Pro_Builder::pct_css',
				'selector' => 'padding-top',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'hero-section-padding-bottom' => array(
				'label'    => __( 'Bottom', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.hero-section',
				'builder'  => 'GP_Pro_Builder::pct_css',
				'selector' => 'padding-bottom',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'hero-section-padding-left'   => array(
				'label'    => __( 'Left', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.hero-section',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-left',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'hero-section-padding-right'  => array(
				'label'    => __( 'Right', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.hero-section',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-right',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
		),
	),

	'section-break-front-page-1'                      => array(
		'break' => array(
			'type'  => 'full',
			'title' => __( 'Front Page 1 Section', 'gppro' ),
			'text'  => __( 'This area is designed to display a featured post widget with an image short excerpt.', 'gppro' ),
		),
	),
	'front-page-1-setup'                              => array(
		'title' => __( 'Padding', 'gppro' ),
		'data'  => array(
			'front-page-1-padding-top'    => array(
				'label'    => __( 'Top', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-1',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-top',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-1-padding-bottom' => array(
				'label'    => __( 'Bottom', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-1',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-bottom',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-1-padding-left'   => array(
				'label'    => __( 'Left', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-1',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-left',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-1-padding-right'  => array(
				'label'    => __( 'Right', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-1',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-right',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
		),
	),

	'section-break-front-page-1-single-widget'        => array(
		'break' => array(
			'type'  => 'full',
			'title' => __( 'Single Widgets', 'gppro' ),
		),
	),
	'front-page-1-widget-back-setup'                  => array(
		'title' => 'Area Setup',
		'data'  => array(
			'front-page-1-widget-back' => array(
				'label'    => __( 'Background Color', 'gppro' ),
				'input'    => 'color',
				'target'   => '.front-page-1 .widget .entry',
				'builder'  => 'GP_Pro_Builder::hexcolor_css',
				'selector' => 'background-color',
			),
		),
	),

	'front-page-1-widget-padding-setup'               => array(
		'title' => __( 'Widget Padding', 'gppro' ),
		'data'  => array(
			'front-page-1-widget-padding-top'    => array(
				'label'    => __( 'Top', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-1 .entry',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-top',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-1-widget-padding-bottom' => array(
				'label'    => __( 'Bottom', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-1 .entry',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-bottom',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-1-widget-padding-left'   => array(
				'label'    => __( 'Left', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-1 .entry',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-left',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-1-widget-padding-right'  => array(
				'label'    => __( 'Right', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-1 .entry',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-right',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
		),
	),

	'section-break-front-page-1-entry-title'          => array(
		'break' => array(
			'type'  => 'thin',
			'title' => __( 'Featured Title', 'gppro' ),
		),
	),
	'front-page-1-post-entry-title-color'             => array(
		'title' => 'Colors',
		'data'  => array(
			'front-page-1-entry-title-link'     => array(
				'label'    => __( 'Link', 'gppro' ),
				'sub'      => __( 'Base', 'gppro' ),
				'input'    => 'color',
				'target'   => '.front-page-1 .entry-title a',
				'builder'  => 'GP_Pro_Builder::hexcolor_css',
				'selector' => 'color',
			),
			'front-page-1-entry-title-link-hov' => array(
				'label'        => __( 'Link', 'gppro' ),
				'sub'          => __( 'Hover', 'gppro' ),
				'input'        => 'color',
				'target'       => array( '.front-page-1 .entry-title a:hover', '.front-page-1 .entry-title a:focus' ),
				'builder'      => 'GP_Pro_Builder::hexcolor_css',
				'selector'     => 'color',
				'always_write' => true,
			),
		),
	),
	'front-page-1-post-entry-title'                   => array(
		'title' => 'Typography',
		'data'  => array(
			'front-page-1-entry-title-stack'     => array(
				'label'    => __( 'Font Stack', 'gppro' ),
				'input'    => 'font-stack',
				'target'   => '.front-page-1 .entry .entry-title',
				'builder'  => 'GP_Pro_Builder::stack_css',
				'selector' => 'font-family',
			),
			'front-page-1-entry-title-size'      => array(
				'label'    => __( 'Font Size', 'gppro' ),
				'input'    => 'font-size',
				'scale'    => 'text',
				'target'   => '.front-page-1 .entry .entry-title',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'font-size',
			),
			'front-page-1-entry-title-weight'    => array(
				'label'    => __( 'Font Weight', 'gppro' ),
				'input'    => 'font-weight',
				'target'   => '.front-page-1 .entry .entry-title',
				'builder'  => 'GP_Pro_Builder::number_css',
				'selector' => 'font-weight',
				'tip'      => __( 'Certain fonts will not display every weight.', 'gppro' ),
			),
			'front-page-1-entry-title-transform' => array(
				'label'    => __( 'Text Appearance', 'gppro' ),
				'input'    => 'text-transform',
				'target'   => '.front-page-1 .entry .entry-title',
				'builder'  => 'GP_Pro_Builder::text_css',
				'selector' => 'text-transform',
			),
			'front-page-1-entry-title-align'     => array(
				'label'        => __( 'Text Alignment', 'gppro' ),
				'input'        => 'text-align',
				'target'       => '.front-page-1 .entry-title',
				'builder'      => 'GP_Pro_Builder::text_css',
				'selector'     => 'text-align',
				'always_write' => true,
			),
			'front-page-1-entry-title-style'     => array(
				'label'    => __( 'Font Style', 'gppro' ),
				'input'    => 'radio',
				'options'  => array(
					array(
						'label' => __( 'Normal', 'gppro' ),
						'value' => 'normal',
					),
					array(
						'label' => __( 'Italic', 'gppro' ),
						'value' => 'italic',
					),
				),
				'target'   => '.front-page-1 .entry .entry-title',
				'builder'  => 'GP_Pro_Builder::text_css',
				'selector' => 'font-style',
			),
		),
	),

	'front-page-1-entry-title-padding-setup'          => array(
		'title' => 'Featured Title Padding',
		'data'  => array(
			'front-page-1-entry-title-padding-top'    => array(
				'label'    => __( 'Top', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-1 .entry-header',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-top',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-1-entry-title-padding-bottom' => array(
				'label'    => __( 'Bottom', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-1 .entry-header',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-bottom',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-1-entry-title-padding-left'   => array(
				'label'    => __( 'Left', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-1 .entry-header',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-left',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-1-entry-title-padding-right'  => array(
				'label'    => __( 'Right', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-1 .entry-header',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-right',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-1-entry-title-margin-setup'   => array(
				'title' => __( 'Featured Title Margin', 'gppro' ),
				'input' => 'divider',
				'style' => 'lines',
			),
			'front-page-1-entry-title-margin-top'     => array(
				'label'    => __( 'Top Margin', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-1 .entry-header',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'margin-top',
				'min'      => '0',
				'max'      => '36',
				'step'     => '2',
			),
			'front-page-1-entry-title-margin-bottom'  => array(
				'label'    => __( 'Bottom Margin', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-1 .entry-header',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'margin-bottom',
				'min'      => '0',
				'max'      => '36',
				'step'     => '2',
			),
			'front-page-1-entry-title-margin-left'    => array(
				'label'    => __( 'Left Margin', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-1 .entry-header',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'margin-left',
				'min'      => '-60',
				'max'      => '36',
				'step'     => '2',
			),
			'front-page-1-entry-title-margin-right'   => array(
				'label'    => __( 'Right Margin', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-1 .entry-header',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'margin-right',
				'min'      => '-60',
				'max'      => '36',
				'step'     => '2',
			),
			'front-page-1-widget-message-divider'     => array(
				'text'  => __( 'Featured Title Margin can be adjusted to re-align title and bottom border if Single Widget padding is adjusted.', 'gppro' ),
				'input' => 'divider',
				'style' => 'block-thin',
			),
		),
	),

	'section-break-front-page-1-widget-meta'          => array(
		'break' => array(
			'type'  => 'thin',
			'title' => __( 'Widget Entry Meta', 'gppro' ),
		),
	),

	'front-page-1-widget-meta-setup'                  => array(
		'title' => '',
		'data'  => array(
			'front-page-1-widget-meta-text'      => array(
				'label'    => __( 'Color', 'gppro' ),
				'input'    => 'color',
				'target'   => array(
					'.front-page-1 .entry .entry-meta',
					'.front-page-1 .entry .entry-meta a',
				),
				'builder'  => 'GP_Pro_Builder::hexcolor_css',
				'selector' => 'color',
			),
			'front-page-1-widget-meta-stack'     => array(
				'label'    => __( 'Font Stack', 'gppro' ),
				'input'    => 'font-stack',
				'target'   => '.front-page-1 .entry .entry-meta',
				'builder'  => 'GP_Pro_Builder::stack_css',
				'selector' => 'font-family',
			),
			'front-page-1-widget-meta-size'      => array(
				'label'    => __( 'Font Size', 'gppro' ),
				'input'    => 'font-size',
				'scale'    => 'text',
				'target'   => '.front-page-1 .entry .entry-meta',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'font-size',
			),
			'front-page-1-widget-meta-weight'    => array(
				'label'    => __( 'Font Weight', 'gppro' ),
				'input'    => 'font-weight',
				'target'   => '.front-page-1 .entry .entry-meta',
				'builder'  => 'GP_Pro_Builder::number_css',
				'selector' => 'font-weight',
				'tip'      => __( 'Certain fonts will not display every weight.', 'gppro' ),
			),
			'front-page-1-widget-meta-transform' => array(
				'label'    => __( 'Text Appearance', 'gppro' ),
				'input'    => 'text-transform',
				'target'   => '.front-page-1 .entry .entry-meta',
				'builder'  => 'GP_Pro_Builder::text_css',
				'selector' => 'text-transform',
			),
			'front-page-1-widget-meta-align'     => array(
				'label'        => __( 'Text Alignment', 'gppro' ),
				'input'        => 'text-align',
				'target'       => '.front-page-1 .entry .entry-meta',
				'builder'      => 'GP_Pro_Builder::text_css',
				'selector'     => 'text-align',
				'always_write' => true,
			),
			'front-page-1-widget-meta-style'     => array(
				'label'    => __( 'Font Style', 'gppro' ),
				'input'    => 'radio',
				'options'  => array(
					array(
						'label' => __( 'Normal', 'gppro' ),
						'value' => 'normal',
					),
					array(
						'label' => __( 'Italic', 'gppro' ),
						'value' => 'italic',
					),
				),
				'target'   => '.front-page-1 .entry .entry-meta',
				'builder'  => 'GP_Pro_Builder::text_css',
				'selector' => 'font-style',
			),
		),
	),

	'section-break-front-page-1-widget-content'       => array(
		'break' => array(
			'type'  => 'thin',
			'title' => __( 'Widget Content', 'gppro' ),
		),
	),

	'front-page-1-widget-content-setup'               => array(
		'title' => '',
		'data'  => array(
			'front-page-1-widget-content-text'      => array(
				'label'    => __( 'Text', 'gppro' ),
				'input'    => 'color',
				'target'   => '.front-page-1 .entry .entry-content',
				'builder'  => 'GP_Pro_Builder::hexcolor_css',
				'selector' => 'color',
			),
			'front-page-1-widget-content-stack'     => array(
				'label'    => __( 'Font Stack', 'gppro' ),
				'input'    => 'font-stack',
				'target'   => '.front-page-1 .entry .entry-content',
				'builder'  => 'GP_Pro_Builder::stack_css',
				'selector' => 'font-family',
			),
			'front-page-1-widget-content-size'      => array(
				'label'    => __( 'Font Size', 'gppro' ),
				'input'    => 'font-size',
				'scale'    => 'text',
				'target'   => '.front-page-1 .entry .entry-content',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'font-size',
			),
			'front-page-1-widget-content-weight'    => array(
				'label'    => __( 'Font Weight', 'gppro' ),
				'input'    => 'font-weight',
				'target'   => '.front-page-1 .entry .entry-content',
				'builder'  => 'GP_Pro_Builder::number_css',
				'selector' => 'font-weight',
				'tip'      => __( 'Certain fonts will not display every weight.', 'gppro' ),
			),
			'front-page-1-widget-content-transform' => array(
				'label'    => __( 'Text Appearance', 'gppro' ),
				'input'    => 'text-transform',
				'target'   => '.front-page-1 .entry .entry-content',
				'builder'  => 'GP_Pro_Builder::text_css',
				'selector' => 'text-transform',
			),
			'front-page-1-widget-content-align'     => array(
				'label'        => __( 'Text Alignment', 'gppro' ),
				'input'        => 'text-align',
				'target'       => '.front-page-1 .entry .entry-content',
				'builder'      => 'GP_Pro_Builder::text_css',
				'selector'     => 'text-align',
				'always_write' => true,
			),
			'front-page-1-widget-content-style'     => array(
				'label'    => __( 'Font Style', 'gppro' ),
				'input'    => 'radio',
				'options'  => array(
					array(
						'label' => __( 'Normal', 'gppro' ),
						'value' => 'normal',
					),
					array(
						'label' => __( 'Italic', 'gppro' ),
						'value' => 'italic',
					),
				),
				'target'   => '.front-page-1 .entry .entry-content',
				'builder'  => 'GP_Pro_Builder::text_css',
				'selector' => 'font-style',
			),
		),
	),

	'section-break-front-page-1-widget-read-more'     => array(
		'break' => array(
			'type'  => 'thin',
			'title' => __( 'Read More Link', 'gppro' ),
		),
	),
	'front-page-1-read-more-color-setup'              => array(
		'title' => 'Colors',
		'data'  => array(
			'front-page-1-read-more-link'            => array(
				'label'        => __( 'Link', 'gppro' ),
				'sub'          => __( 'base', 'gppro' ),
				'input'        => 'color',
				'target'       => '.front-page-1 .entry-content .more-link-wrap a.more-link',
				'builder'      => 'GP_Pro_Builder::hexcolor_css',
				'selector'     => 'color',
				'always_write' => true,
			),
			'front-page-1-read-more-link-hov'        => array(
				'label'        => __( 'Link', 'gppro' ),
				'sub'          => __( 'Hover', 'gppro' ),
				'input'        => 'color',
				'target'       => array( '.front-page-1 .entry-content .more-link-wrap a.more-link:hover, .front-page-1 .entry-content .more-link-wrap a.more-link:focus' ),
				'builder'      => 'GP_Pro_Builder::hexcolor_css',
				'selector'     => 'color',
				'always_write' => true,
			),
			'front-page-1-read-more-underline-color' => array(
				'label'        => __( 'Bottom Border Color', 'gppro' ),
				'input'        => 'color',
				'target'       => '.front-page-1 .entry-content .more-link-wrap a.more-link',
				'builder'      => 'GP_Pro_Builder::hexcolor_css',
				'selector'     => 'border-bottom-color',
				'always_write' => true,
			),
			'front-page-1-read-more-underline-hov'   => array(
				'label'        => __( 'Bottom Border Color', 'gppro' ),
				'sub'          => __( 'Hover', 'gppro' ),
				'input'        => 'color',
				'target'       => array( '.front-page-1 .entry-content .more-link-wrap a.more-link:hover, .front-page-1 .entry-content .more-link-wrap a.more-link:focus' ),
				'builder'      => 'GP_Pro_Builder::hexcolor_css',
				'selector'     => 'border-bottom-color',
				'always_write' => true,
			),
			'front-page-1-read-more-underline-style' => array(
				'label'    => __( 'Bottom Border Style', 'gppro' ),
				'input'    => 'borders',
				'target'   => '.front-page-1 .entry-content .more-link-wrap a.more-link',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'border-bottom-style',
			),
			'front-page-1-read-more-underline-width' => array(
				'label'    => __( 'Bottom Border Width', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-1 .entry-content .more-link-wrap a.more-link',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'border-bottom-width',
				'min'      => '0',
				'max'      => '10',
				'step'     => '1',
			),
		),
	),
	'front-page-1-read-more-setup'                    => array(
		'title' => 'Typography',
		'data'  => array(
			'front-page-1-read-more-stack'     => array(
				'label'    => __( 'Font Stack', 'gppro' ),
				'input'    => 'font-stack',
				'target'   => '.front-page-1 .more-link',
				'builder'  => 'GP_Pro_Builder::stack_css',
				'selector' => 'font-family',
			),
			'front-page-1-read-more-size'      => array(
				'label'    => __( 'Font Size', 'gppro' ),
				'input'    => 'font-size',
				'scale'    => 'text',
				'target'   => '.front-page-1 .more-link',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'font-size',
			),
			'front-page-1-read-more-weight'    => array(
				'label'    => __( 'Font Weight', 'gppro' ),
				'input'    => 'font-weight',
				'target'   => '.front-page-1 .more-link',
				'builder'  => 'GP_Pro_Builder::number_css',
				'selector' => 'font-weight',
				'tip'      => __( 'Certain fonts will not display every weight.', 'gppro' ),
			),
			'front-page-1-read-more-transform' => array(
				'label'    => __( 'Text Appearance', 'gppro' ),
				'input'    => 'text-transform',
				'target'   => '.front-page-1 .more-link',
				'builder'  => 'GP_Pro_Builder::text_css',
				'selector' => 'text-transform',
			),
			'front-page-1-read-more-align'     => array(
				'label'        => __( 'Text Alignment', 'gppro' ),
				'input'        => 'text-align',
				'target'       => '.front-page-1 .more-link',
				'builder'      => 'GP_Pro_Builder::text_css',
				'selector'     => 'text-align',
				'always_write' => true,
			),
			'front-page-1-read-more-style'     => array(
				'label'    => __( 'Font Style', 'gppro' ),
				'input'    => 'radio',
				'options'  => array(
					array(
						'label' => __( 'Normal', 'gppro' ),
						'value' => 'normal',
					),
					array(
						'label' => __( 'Italic', 'gppro' ),
						'value' => 'italic',
					),
				),
				'target'   => '.front-page-1 .entry .more-link',
				'builder'  => 'GP_Pro_Builder::text_css',
				'selector' => 'font-style',
			),
		),
	),

	'section-break-front-page-2'                      => array(
		'break' => array(
			'type'  => 'full',
			'title' => __( 'Front Page 2 Section', 'gppro' ),
			'text'  => __( 'This area is designed to display a featured post widget with an image and title.', 'gppro' ),
		),
	),
	'front-page-2-setup'                              => array(
		'title' => __( 'Padding', 'gppro' ),
		'data'  => array(
			'front-page-2-padding-top'    => array(
				'label'    => __( 'Top', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-2',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-top',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-2-padding-bottom' => array(
				'label'    => __( 'Bottom', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-2',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-bottom',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-2-padding-left'   => array(
				'label'    => __( 'Left', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-2',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-left',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-2-padding-right'  => array(
				'label'    => __( 'Right', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-2',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-right',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
		),
	),

	'section-break-front-page-2-single-widget'        => array(
		'break' => array(
			'type'  => 'full',
			'title' => __( 'Single Widgets', 'gppro' ),
		),
	),
	'front-page-2-widget-back-setup'                  => array(
		'title' => 'Area Setup',
		'data'  => array(
			'front-page-2-widget-back' => array(
				'label'    => __( 'Background Color', 'gppro' ),
				'input'    => 'color',
				'target'   => '.front-page-2 .widget .entry',
				'builder'  => 'GP_Pro_Builder::hexcolor_css',
				'selector' => 'background-color',
			),
		),
	),

	'front-page-2-widget-padding-setup'               => array(
		'title' => __( 'Widget Padding', 'gppro' ),
		'data'  => array(
			'front-page-2-widget-padding-top'    => array(
				'label'    => __( 'Top', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-2 .entry',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-top',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-2-widget-padding-bottom' => array(
				'label'    => __( 'Bottom', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-2 .entry',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-bottom',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-2-widget-padding-left'   => array(
				'label'    => __( 'Left', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-2 .entry',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-left',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-2-widget-padding-right'  => array(
				'label'    => __( 'Right', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-2 .entry',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-right',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
		),
	),

	'section-break-front-page-2-entry-title'          => array(
		'break' => array(
			'type'  => 'thin',
			'title' => __( 'Featured Title', 'gppro' ),
		),
	),
	'front-page-2-post-entry-title-color'             => array(
		'title' => 'Colors',
		'data'  => array(
			'front-page-2-entry-title-link'     => array(
				'label'    => __( 'Link', 'gppro' ),
				'sub'      => __( 'Base', 'gppro' ),
				'input'    => 'color',
				'target'   => '.front-page-2 .entry-title a',
				'builder'  => 'GP_Pro_Builder::hexcolor_css',
				'selector' => 'color',
			),
			'front-page-2-entry-title-link-hov' => array(
				'label'        => __( 'Link', 'gppro' ),
				'sub'          => __( 'Hover', 'gppro' ),
				'input'        => 'color',
				'target'       => array( '.front-page-2 .entry-title a:hover', '.front-page-2 .entry-title a:focus' ),
				'builder'      => 'GP_Pro_Builder::hexcolor_css',
				'selector'     => 'color',
				'always_write' => true,
			),
		),
	),
	'front-page-2-post-entry-title'                   => array(
		'title' => 'Typography',
		'data'  => array(
			'front-page-2-entry-title-stack'     => array(
				'label'    => __( 'Font Stack', 'gppro' ),
				'input'    => 'font-stack',
				'target'   => '.front-page-2 .entry .entry-title',
				'builder'  => 'GP_Pro_Builder::stack_css',
				'selector' => 'font-family',
			),
			'front-page-2-entry-title-size'      => array(
				'label'    => __( 'Font Size', 'gppro' ),
				'input'    => 'font-size',
				'scale'    => 'text',
				'target'   => '.front-page-2 .entry .entry-title',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'font-size',
			),
			'front-page-2-entry-title-weight'    => array(
				'label'    => __( 'Font Weight', 'gppro' ),
				'input'    => 'font-weight',
				'target'   => '.front-page-2 .entry .entry-title',
				'builder'  => 'GP_Pro_Builder::number_css',
				'selector' => 'font-weight',
				'tip'      => __( 'Certain fonts will not display every weight.', 'gppro' ),
			),
			'front-page-2-entry-title-transform' => array(
				'label'    => __( 'Text Appearance', 'gppro' ),
				'input'    => 'text-transform',
				'target'   => '.front-page-2 .entry .entry-title',
				'builder'  => 'GP_Pro_Builder::text_css',
				'selector' => 'text-transform',
			),
			'front-page-2-entry-title-align'     => array(
				'label'        => __( 'Text Alignment', 'gppro' ),
				'input'        => 'text-align',
				'target'       => '.front-page-2 .entry-title',
				'builder'      => 'GP_Pro_Builder::text_css',
				'selector'     => 'text-align',
				'always_write' => true,
			),
			'front-page-2-entry-title-style'     => array(
				'label'    => __( 'Font Style', 'gppro' ),
				'input'    => 'radio',
				'options'  => array(
					array(
						'label' => __( 'Normal', 'gppro' ),
						'value' => 'normal',
					),
					array(
						'label' => __( 'Italic', 'gppro' ),
						'value' => 'italic',
					),
				),
				'target'   => '.front-page-2 .entry .entry-title',
				'builder'  => 'GP_Pro_Builder::text_css',
				'selector' => 'font-style',
			),
		),
	),

	'front-page-2-entry-title-padding-setup'          => array(
		'title' => 'Featured Title Padding',
		'data'  => array(
			'front-page-2-entry-title-padding-top'    => array(
				'label'    => __( 'Top', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-2 .entry-header',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-top',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-2-entry-title-padding-bottom' => array(
				'label'    => __( 'Bottom', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-2 .entry-header',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-bottom',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-2-entry-title-padding-left'   => array(
				'label'    => __( 'Left', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-2 .entry-header',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-left',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-2-entry-title-padding-right'  => array(
				'label'    => __( 'Right', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-2 .entry-header',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-right',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-2-entry-title-margin-setup'   => array(
				'title' => __( 'Featured Title Margin', 'gppro' ),
				'input' => 'divider',
				'style' => 'lines',
			),
			'front-page-2-entry-title-margin-top'     => array(
				'label'    => __( 'Top Margin', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-2 .entry-header',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'margin-top',
				'min'      => '0',
				'max'      => '36',
				'step'     => '2',
			),
			'front-page-2-entry-title-margin-bottom'  => array(
				'label'    => __( 'Bottom Margin', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-2 .entry-header',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'margin-bottom',
				'min'      => '0',
				'max'      => '36',
				'step'     => '2',
			),
			'front-page-2-entry-title-margin-left'    => array(
				'label'    => __( 'Left Margin', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-2 .entry-header',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'margin-left',
				'min'      => '-60',
				'max'      => '36',
				'step'     => '2',
			),
			'front-page-2-entry-title-margin-right'   => array(
				'label'    => __( 'Right Margin', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-2 .entry-header',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'margin-right',
				'min'      => '-60',
				'max'      => '36',
				'step'     => '2',
			),
			'front-page-2-widget-message-divider'     => array(
				'text'  => __( 'Featured Title Margin can be adjusted to re-align title and bottom border if Single Widget padding is adjusted.', 'gppro' ),
				'input' => 'divider',
				'style' => 'block-thin',
			),
		),
	),

	'section-break-front-page-2-widget-content'       => array(
		'break' => array(
			'type'  => 'thin',
			'title' => __( 'Widget Content', 'gppro' ),
		),
	),

	'front-page-2-widget-content-setup'               => array(
		'title' => '',
		'data'  => array(
			'front-page-2-widget-content-text'      => array(
				'label'    => __( 'Text', 'gppro' ),
				'input'    => 'color',
				'target'   => '.front-page-2 .entry .entry-content',
				'builder'  => 'GP_Pro_Builder::hexcolor_css',
				'selector' => 'color',
			),
			'front-page-2-widget-content-stack'     => array(
				'label'    => __( 'Font Stack', 'gppro' ),
				'input'    => 'font-stack',
				'target'   => '.front-page-2 .entry .entry-content',
				'builder'  => 'GP_Pro_Builder::stack_css',
				'selector' => 'font-family',
			),
			'front-page-2-widget-content-size'      => array(
				'label'    => __( 'Font Size', 'gppro' ),
				'input'    => 'font-size',
				'scale'    => 'text',
				'target'   => '.front-page-2 .entry .entry-content',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'font-size',
			),
			'front-page-2-widget-content-weight'    => array(
				'label'    => __( 'Font Weight', 'gppro' ),
				'input'    => 'font-weight',
				'target'   => '.front-page-2 .entry .entry-content',
				'builder'  => 'GP_Pro_Builder::number_css',
				'selector' => 'font-weight',
				'tip'      => __( 'Certain fonts will not display every weight.', 'gppro' ),
			),
			'front-page-2-widget-content-transform' => array(
				'label'    => __( 'Text Appearance', 'gppro' ),
				'input'    => 'text-transform',
				'target'   => '.front-page-2 .entry .entry-content',
				'builder'  => 'GP_Pro_Builder::text_css',
				'selector' => 'text-transform',
			),
			'front-page-2-widget-content-align'     => array(
				'label'        => __( 'Text Alignment', 'gppro' ),
				'input'        => 'text-align',
				'target'       => '.front-page-2 .entry .entry-content',
				'builder'      => 'GP_Pro_Builder::text_css',
				'selector'     => 'text-align',
				'always_write' => true,
			),
			'front-page-2-widget-content-style'     => array(
				'label'    => __( 'Font Style', 'gppro' ),
				'input'    => 'radio',
				'options'  => array(
					array(
						'label' => __( 'Normal', 'gppro' ),
						'value' => 'normal',
					),
					array(
						'label' => __( 'Italic', 'gppro' ),
						'value' => 'italic',
					),
				),
				'target'   => '.front-page-2 .entry .entry-content',
				'builder'  => 'GP_Pro_Builder::text_css',
				'selector' => 'font-style',
			),
		),
	),

	'section-break-front-page-2-widget-read-more'     => array(
		'break' => array(
			'type'  => 'thin',
			'title' => __( 'Read More Link', 'gppro' ),
		),
	),
	'front-page-2-read-more-color-setup'              => array(
		'title' => 'Colors',
		'data'  => array(
			'front-page-2-read-more-link'            => array(
				'label'        => __( 'Link', 'gppro' ),
				'sub'          => __( 'base', 'gppro' ),
				'input'        => 'color',
				'target'       => '.front-page-2 .entry-content .more-link-wrap a.more-link',
				'builder'      => 'GP_Pro_Builder::hexcolor_css',
				'selector'     => 'color',
				'always_write' => true,
			),
			'front-page-2-read-more-link-hov'        => array(
				'label'        => __( 'Link', 'gppro' ),
				'sub'          => __( 'Hover', 'gppro' ),
				'input'        => 'color',
				'target'       => array( '.front-page-2 .entry-content .more-link-wrap a.more-link:hover, .front-page-2 .entry-content .more-link-wrap a.more-link:focus' ),
				'builder'      => 'GP_Pro_Builder::hexcolor_css',
				'selector'     => 'color',
				'always_write' => true,
			),
			'front-page-2-read-more-underline-color' => array(
				'label'        => __( 'Bottom Border Color', 'gppro' ),
				'input'        => 'color',
				'target'       => '.front-page-2 .entry-content .more-link-wrap a.more-link',
				'builder'      => 'GP_Pro_Builder::hexcolor_css',
				'selector'     => 'border-bottom-color',
				'always_write' => true,
			),
			'front-page-2-read-more-underline-hov'   => array(
				'label'        => __( 'Bottom Border Color', 'gppro' ),
				'sub'          => __( 'Hover', 'gppro' ),
				'input'        => 'color',
				'target'       => array( '.front-page-2 .entry-content .more-link-wrap a.more-link:hover, .front-page-2 .entry-content .more-link-wrap a.more-link:focus' ),
				'builder'      => 'GP_Pro_Builder::hexcolor_css',
				'selector'     => 'border-bottom-color',
				'always_write' => true,
			),
			'front-page-2-read-more-underline-style' => array(
				'label'    => __( 'Bottom Border Style', 'gppro' ),
				'input'    => 'borders',
				'target'   => '.front-page-2 .entry-content .more-link-wrap a.more-link',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'border-bottom-style',
			),
			'front-page-2-read-more-underline-width' => array(
				'label'    => __( 'Bottom Border Width', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-2 .entry-content .more-link-wrap a.more-link',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'border-bottom-width',
				'min'      => '0',
				'max'      => '10',
				'step'     => '1',
			),
		),
	),
	'front-page-2-read-more-setup'                    => array(
		'title' => 'Typography',
		'data'  => array(
			'front-page-2-read-more-stack'     => array(
				'label'    => __( 'Font Stack', 'gppro' ),
				'input'    => 'font-stack',
				'target'   => '.front-page-2 .more-link',
				'builder'  => 'GP_Pro_Builder::stack_css',
				'selector' => 'font-family',
			),
			'front-page-2-read-more-size'      => array(
				'label'    => __( 'Font Size', 'gppro' ),
				'input'    => 'font-size',
				'scale'    => 'text',
				'target'   => '.front-page-2 .more-link',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'font-size',
			),
			'front-page-2-read-more-weight'    => array(
				'label'    => __( 'Font Weight', 'gppro' ),
				'input'    => 'font-weight',
				'target'   => '.front-page-2 .more-link',
				'builder'  => 'GP_Pro_Builder::number_css',
				'selector' => 'font-weight',
				'tip'      => __( 'Certain fonts will not display every weight.', 'gppro' ),
			),
			'front-page-2-read-more-transform' => array(
				'label'    => __( 'Text Appearance', 'gppro' ),
				'input'    => 'text-transform',
				'target'   => '.front-page-2 .more-link',
				'builder'  => 'GP_Pro_Builder::text_css',
				'selector' => 'text-transform',
			),
			'front-page-2-read-more-align'     => array(
				'label'        => __( 'Text Alignment', 'gppro' ),
				'input'        => 'text-align',
				'target'       => '.front-page-2 .more-link',
				'builder'      => 'GP_Pro_Builder::text_css',
				'selector'     => 'text-align',
				'always_write' => true,
			),
			'front-page-2-read-more-style'     => array(
				'label'    => __( 'Font Style', 'gppro' ),
				'input'    => 'radio',
				'options'  => array(
					array(
						'label' => __( 'Normal', 'gppro' ),
						'value' => 'normal',
					),
					array(
						'label' => __( 'Italic', 'gppro' ),
						'value' => 'italic',
					),
				),
				'target'   => '.front-page-2 .entry .more-link',
				'builder'  => 'GP_Pro_Builder::text_css',
				'selector' => 'font-style',
			),
		),
	),

	'section-break-front-page-featured'               => array(
		'break' => array(
			'type'  => 'full',
			'title' => __( 'Front Page Featured', 'gppro' ),
			'text'  => __( 'This area is designed to display a custom HTML widget with a blockquote and citation.', 'gppro' ),
		),
	),
	'front-page-featured-widget-setup'                => array(
		'title' => __( 'Area Setup', 'gppro' ),
		'data'  => array(
			'front-page-featured-back' => array(
				'label'    => __( 'Background Color', 'gppro' ),
				'input'    => 'color',
				'target'   => '.front-page-featured',
				'builder'  => 'GP_Pro_Builder::hexcolor_css',
				'selector' => 'background-color',
			),
		),
	),
	'front-page-featured-setup'                       => array(
		'title' => __( 'Padding', 'gppro' ),
		'data'  => array(
			'front-page-featured-padding-top'    => array(
				'label'    => __( 'Top', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-featured',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-top',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-featured-padding-bottom' => array(
				'label'    => __( 'Bottom', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-featured',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-bottom',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-featured-padding-left'   => array(
				'label'    => __( 'Left', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-featured',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-left',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-featured-padding-right'  => array(
				'label'    => __( 'Right', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-featured',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-right',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
		),
	),

	'section-break-front-page-featured-single-widget' => array(
		'break' => array(
			'type'  => 'full',
			'title' => __( 'Single Widgets', 'gppro' ),
		),
	),
	'front-page-featured-widget-back-setup'           => array(
		'title' => 'Area Setup',
		'data'  => array(
			'front-page-featured-widget-back' => array(
				'label'    => __( 'Background Color', 'gppro' ),
				'input'    => 'color',
				'target'   => '.front-page-featured .widget',
				'builder'  => 'GP_Pro_Builder::hexcolor_css',
				'selector' => 'background-color',
			),
		),
	),

	'front-page-featured-widget-padding-setup'        => array(
		'title' => __( 'Widget Padding', 'gppro' ),
		'data'  => array(
			'front-page-featured-widget-padding-top'    => array(
				'label'    => __( 'Top', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-featured .widget',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-top',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-featured-widget-padding-bottom' => array(
				'label'    => __( 'Bottom', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-featured .widget',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-bottom',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-featured-widget-padding-left'   => array(
				'label'    => __( 'Left', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-featured .widget',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-left',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-featured-widget-padding-right'  => array(
				'label'    => __( 'Right', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-featured .widget',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-right',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
		),
	),

	'section-break-front-page-featured-blockquote'    => array(
		'break' => array(
			'type'  => 'thin',
			'title' => __( 'Blockquote', 'gppro' ),
		),
	),
	'front-page-featured-blockquote-color'            => array(
		'title' => 'Colors',
		'data'  => array(
			'front-page-featured-blockquote-color' => array(
				'label'    => __( 'Link', 'gppro' ),
				'sub'      => __( 'Base', 'gppro' ),
				'input'    => 'color',
				'target'   => '.front-page-featured blockquote',
				'builder'  => 'GP_Pro_Builder::hexcolor_css',
				'selector' => 'color',
			),
		),
	),
	'front-page-featured-blockquote'                  => array(
		'title' => 'Typography',
		'data'  => array(
			'front-page-featured-blockquote-stack'     => array(
				'label'    => __( 'Font Stack', 'gppro' ),
				'input'    => 'font-stack',
				'target'   => '.front-page-featured blockquote',
				'builder'  => 'GP_Pro_Builder::stack_css',
				'selector' => 'font-family',
			),
			'front-page-featured-blockquote-size'      => array(
				'label'    => __( 'Font Size', 'gppro' ),
				'input'    => 'font-size',
				'scale'    => 'text',
				'target'   => '.front-page-featured blockquote',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'font-size',
			),
			'front-page-featured-blockquote-weight'    => array(
				'label'    => __( 'Font Weight', 'gppro' ),
				'input'    => 'font-weight',
				'target'   => '.front-page-featured blockquote',
				'builder'  => 'GP_Pro_Builder::number_css',
				'selector' => 'font-weight',
				'tip'      => __( 'Certain fonts will not display every weight.', 'gppro' ),
			),
			'front-page-featured-blockquote-transform' => array(
				'label'    => __( 'Text Appearance', 'gppro' ),
				'input'    => 'text-transform',
				'target'   => '.front-page-featured blockquote',
				'builder'  => 'GP_Pro_Builder::text_css',
				'selector' => 'text-transform',
			),
			'front-page-featured-blockquote-align'     => array(
				'label'        => __( 'Text Alignment', 'gppro' ),
				'input'        => 'text-align',
				'target'       => '.front-page-featured blockquote',
				'builder'      => 'GP_Pro_Builder::text_css',
				'selector'     => 'text-align',
				'always_write' => true,
			),
			'front-page-featured-blockquote-style'     => array(
				'label'    => __( 'Font Style', 'gppro' ),
				'input'    => 'radio',
				'options'  => array(
					array(
						'label' => __( 'Normal', 'gppro' ),
						'value' => 'normal',
					),
					array(
						'label' => __( 'Italic', 'gppro' ),
						'value' => 'italic',
					),
				),
				'target'   => '.front-page-featured blockquote',
				'builder'  => 'GP_Pro_Builder::text_css',
				'selector' => 'font-style',
			),
		),
	),

	'front-page-featured-blockquote-padding-setup'    => array(
		'title' => __( 'Featured Blockquote Padding', 'gppro' ),
		'data'  => array(
			'front-page-featured-blockquote-padding-top'   => array(
				'label'    => __( 'Top', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-featured blockquote',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-top',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-featured-blockquote-padding-bottom' => array(
				'label'    => __( 'Bottom', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-featured blockquote',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-bottom',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-featured-blockquote-padding-left'  => array(
				'label'    => __( 'Left', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-featured blockquote',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-left',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-featured-blockquote-padding-right' => array(
				'label'    => __( 'Right', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-featured blockquote',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-right',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-featured-blockquote-margin-setup'  => array(
				'title' => __( 'Featured Blockquote Margin', 'gppro' ),
				'input' => 'divider',
				'style' => 'lines',
			),
			'front-page-featured-blockquote-margin-top'    => array(
				'label'    => __( 'Top Margin', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-featured blockquote',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'margin-top',
				'min'      => '0',
				'max'      => '36',
				'step'     => '2',
			),
			'front-page-featured-blockquote-margin-bottom' => array(
				'label'    => __( 'Bottom Margin', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-featured blockquote',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'margin-bottom',
				'min'      => '0',
				'max'      => '36',
				'step'     => '2',
			),
			'front-page-featured-blockquote-margin-left'   => array(
				'label'    => __( 'Left Margin', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-featured blockquote',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'margin-left',
				'min'      => '-60',
				'max'      => '36',
				'step'     => '2',
			),
			'front-page-featured-blockquote-margin-right'  => array(
				'label'    => __( 'Right Margin', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-featured blockquote',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'margin-right',
				'min'      => '-60',
				'max'      => '36',
				'step'     => '2',
			),
			'front-page-featured-widget-message-divider'   => array(
				'text'  => __( 'Featured Title Margin can be adjusted to re-align title and bottom border if Single Widget padding is adjusted.', 'gppro' ),
				'input' => 'divider',
				'style' => 'block-thin',
			),
		),
	),

	'section-break-front-page-featured-cite'          => array(
		'break' => array(
			'type'  => 'thin',
			'title' => __( 'Citation', 'gppro' ),
		),
	),
	'front-page-featured-cite-color'                  => array(
		'title' => __( 'Colors', 'gppro' ),
		'data'  => array(
			'front-page-featured-cite-color' => array(
				'label'    => __( 'Link', 'gppro' ),
				'sub'      => __( 'Base', 'gppro' ),
				'input'    => 'color',
				'target'   => '.front-page-featured cite',
				'builder'  => 'GP_Pro_Builder::hexcolor_css',
				'selector' => 'color',
			),
		),
	),
	'front-page-featured-cite'                        => array(
		'title' => __( 'Typography', 'gppro' ),
		'data'  => array(
			'front-page-featured-cite-stack'     => array(
				'label'    => __( 'Font Stack', 'gppro' ),
				'input'    => 'font-stack',
				'target'   => '.front-page-featured cite',
				'builder'  => 'GP_Pro_Builder::stack_css',
				'selector' => 'font-family',
			),
			'front-page-featured-cite-size'      => array(
				'label'    => __( 'Font Size', 'gppro' ),
				'input'    => 'font-size',
				'scale'    => 'text',
				'target'   => '.front-page-featured cite',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'font-size',
			),
			'front-page-featured-cite-weight'    => array(
				'label'    => __( 'Font Weight', 'gppro' ),
				'input'    => 'font-weight',
				'target'   => '.front-page-featured cite',
				'builder'  => 'GP_Pro_Builder::number_css',
				'selector' => 'font-weight',
				'tip'      => __( 'Certain fonts will not display every weight.', 'gppro' ),
			),
			'front-page-featured-cite-transform' => array(
				'label'    => __( 'Text Appearance', 'gppro' ),
				'input'    => 'text-transform',
				'target'   => '.front-page-featured cite',
				'builder'  => 'GP_Pro_Builder::text_css',
				'selector' => 'text-transform',
			),
			'front-page-featured-cite-align'     => array(
				'label'        => __( 'Text Alignment', 'gppro' ),
				'input'        => 'text-align',
				'target'       => '.front-page-featured cite',
				'builder'      => 'GP_Pro_Builder::text_css',
				'selector'     => 'text-align',
				'always_write' => true,
			),
			'front-page-featured-cite-style'     => array(
				'label'    => __( 'Font Style', 'gppro' ),
				'input'    => 'radio',
				'options'  => array(
					array(
						'label' => __( 'Normal', 'gppro' ),
						'value' => 'normal',
					),
					array(
						'label' => __( 'Italic', 'gppro' ),
						'value' => 'italic',
					),
				),
				'target'   => '.front-page-featured cite',
				'builder'  => 'GP_Pro_Builder::text_css',
				'selector' => 'font-style',
			),
		),
	),

	'front-page-featured-cite-padding-setup'          => array(
		'title' => __( 'Featured Citation Padding', 'gppro' ),
		'data'  => array(
			'front-page-featured-cite-padding-top'       => array(
				'label'    => __( 'Top', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-featured cite',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-top',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-featured-cite-padding-bottom'    => array(
				'label'    => __( 'Bottom', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-featured cite',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-bottom',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-featured-cite-padding-left'      => array(
				'label'    => __( 'Left', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-featured cite',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-left',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-featured-cite-padding-right'     => array(
				'label'    => __( 'Right', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-featured cite',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'padding-right',
				'min'      => '0',
				'max'      => '60',
				'step'     => '2',
			),
			'front-page-featured-cite-margin-setup'      => array(
				'title' => __( 'Featured Citation Margin', 'gppro' ),
				'input' => 'divider',
				'style' => 'lines',
			),
			'front-page-featured-cite-margin-top'        => array(
				'label'    => __( 'Top Margin', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-featured cite',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'margin-top',
				'min'      => '0',
				'max'      => '36',
				'step'     => '2',
			),
			'front-page-featured-cite-margin-bottom'     => array(
				'label'    => __( 'Bottom Margin', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-featured cite',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'margin-bottom',
				'min'      => '0',
				'max'      => '36',
				'step'     => '2',
			),
			'front-page-featured-cite-margin-left'       => array(
				'label'    => __( 'Left Margin', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-featured cite',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'margin-left',
				'min'      => '-60',
				'max'      => '36',
				'step'     => '2',
			),
			'front-page-featured-cite-margin-right'      => array(
				'label'    => __( 'Right Margin', 'gppro' ),
				'input'    => 'spacing',
				'target'   => '.front-page-featured cite',
				'builder'  => 'GP_Pro_Builder::px_css',
				'selector' => 'margin-right',
				'min'      => '-60',
				'max'      => '36',
				'step'     => '2',
			),
			'front-page-featured-widget-message-divider' => array(
				'text'  => __( 'Featured Title Margin can be adjusted to re-align title and bottom border if Single Widget padding is adjusted.', 'gppro' ),
				'input' => 'divider',
				'style' => 'block-thin',
			),
		),
	),
);
